"""change user profile error

Revision ID: 593f65c4ed0a
Revises: ec0200e548ca
Create Date: 2017-08-23 09:48:24.475697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '593f65c4ed0a'
down_revision = 'ec0200e548ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('localtion', sa.String(length=64), nullable=True))
    op.drop_column('users', 'locaition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locaition', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'localtion')
    # ### end Alembic commands ###
